//
// Future.java -- Java interface Future
// Project OrcJava
//
// $Id$
//
// Copyright (c) 2009 The University of Texas at Austin. All rights reserved.
//
// Use and redistribution of this file is governed by the license terms in
// the LICENSE file found in the project's top-level directory and also found at
// URL: http://orc.csres.utexas.edu/license.shtml .
//

package orc.runtime.values;

import orc.error.runtime.UncallableValueException;
import orc.runtime.Token;

/**
 * Interface for values which may be unbound (i.e. those generated by asymmetric
 * composition). Any class implementing Future can be forced to try and obtain
 * its bound value.
 * 
 * @see Value#forceArg(Object, Token)
 * @see Value#forceCall(Object, Token)
 * @author dkitchin
 */
public interface Future {
	public Callable forceCall(Token t) throws UncallableValueException;

	public Object forceArg(Token t);
}
