--
-- prelude.inc -- Orc standard prelude include file
-- Project OrcJava
--
-- $Id$
--
-- Copyright (c) 2009 The University of Texas at Austin. All rights reserved.
--
-- Use and redistribution of this file is governed by the license terms in
-- the LICENSE file found in the project's top-level directory and also found at
-- URL: http://orc.csres.utexas.edu/license.shtml .
--

include "prelude/core.inc"
--FIXME:include "prelude/state.inc"
--FIXME:include "prelude/time.inc"
--FIXME:include "prelude/idioms.inc"
--FIXME:include "prelude/list.inc"
include "prelude/text.inc"
--FIXME:include "prelude/util.inc"
--FIXME:include "prelude/reflect.inc"
