package orc.error;

/**
 * 
 * Any exception generated by Orc, during compilation, loading, or execution.
 * Though sites written in Java will sometimes produce java-level exceptions,
 * those exceptions are wrapped in a subclass of OrcException to localize and
 * isolate failures (see LocalException, JavaException).
 * 
 * @author dkitchin
 *
 */
public class OrcException extends Exception {
	
	public OrcException(String message) {
		super(message);
	}

	public OrcException(String message, Throwable cause) {
		super(message, cause);
	}
	
	public OrcException(Throwable cause) {
		super(cause);
	}
}
