site cat = orc.lib.str.Cat
site print = orc.lib.str.Print
site println = orc.lib.str.Println

site random = orc.lib.util.Random
site UUID = orc.lib.util.UUID
site Thread = orc.lib.util.ThreadSite
site Null = orc.lib.util.JavaNull

site Buffer = orc.lib.state.Buffer
site SyncChannel = orc.lib.state.SyncChannel
site Cell = orc.lib.state.Cell
site Ref = orc.lib.state.Ref

site parseInt = orc.lib.str.AtoI
site parseBool = orc.lib.str.AtoB