/**
 * Fundamental sites. Specifically, these sites
 * may be generated by the compiler as it desugars
 * patterns, so they absolutely must be supported
 * by any Orc engine.
 */

package orc.runtime.sites.core;