package orc.orchard;

import java.util.Date;

import orc.orchard.jmx.JMXDescription;


public interface JobMBean {
	@JMXDescription("When was this job started?")
	public Date getStartDate();
	@JMXDescription("What state is this job in?")
	public String getState();
	@JMXDescription("Stop the job (but do not remove it)")
	public void halt();
	@JMXDescription("Stop the job and remove it")
	public void finish();
	@JMXDescription("Return the total number of events generated by the job")
	public int getTotalNumEvents();
}
