site "op+" = orc.lib.math.Add
site "op-" = orc.lib.math.Sub
site "op*" = orc.lib.math.Mult
site "op/" = orc.lib.math.Div
site "op%" = orc.lib.math.Mod
site "opu-" = orc.lib.math.UMinus

site "op<" = orc.lib.comp.Less
site "op<=" = orc.lib.comp.Leq
site "op>" = orc.lib.comp.Greater
site "op>=" = orc.lib.comp.Greq


site "op=" = orc.runtime.sites.core.Equal
site "op/=" = orc.runtime.sites.core.Inequal

site "op~" = orc.runtime.sites.core.Not

site "op&&" = orc.lib.bool.And
site "op||" = orc.lib.bool.Or






