--
-- web.inc -- Orc standard prelude include, web section
-- Project OrcScala
--
-- $Id: util.inc 2364 2011-01-24 07:16:15Z dkitchin $
--
-- Copyright (c) 2011 The University of Texas at Austin. All rights reserved.
--
-- Use and redistribution of this file is governed by the license terms in
-- the LICENSE file found in the project's top-level directory and also found at
-- URL: http://orc.csres.utexas.edu/license.shtml .
--

{- Browser -}
site Browse = orc.lib.web.Browse
