package orc.orcx;

import orc.runtime.values.Value;

import org.exist.xquery.value.NodeValue;

/**
 * 
 * An Orc value encapsulating an XML document node generated by XQuery. 
 * 
 * @author dkitchin
 *
 */

public class XMLNode extends Value {

	NodeValue node;
	
	public XMLNode(NodeValue node) {
		this.node = node;
	}
	
	public NodeValue getNode() {
		return this.node;
	}
	
	public String toString() {
		return this.node.toString();
	}
	
}
